version: '3'

services:
  invoice_ocr:
    build: .
    container_name: invoice_ocr
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./app/static/uploads:/app/app/static/uploads
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
    networks:
      - invoice_ocr_network

networks:
  invoice_ocr_network:
    driver: bridge 