"""initial schema with existing models

Revision ID: 00a9278a5b2a
Revises: 
Create Date: 2026-04-16 03:34:29.919944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a9278a5b2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_type', sa.String(length=50), nullable=True),
    sa.Column('invoice_code', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('invoice_date_raw', sa.String(length=50), nullable=True),
    sa.Column('check_code', sa.String(length=100), nullable=True),
    sa.Column('machine_number', sa.String(length=50), nullable=True),
    sa.Column('seller_name', sa.String(length=100), nullable=True),
    sa.Column('seller_tax_id', sa.String(length=50), nullable=True),
    sa.Column('seller_address', sa.String(length=200), nullable=True),
    sa.Column('seller_bank_info', sa.String(length=200), nullable=True),
    sa.Column('buyer_name', sa.String(length=100), nullable=True),
    sa.Column('buyer_tax_id', sa.String(length=50), nullable=True),
    sa.Column('buyer_address', sa.String(length=200), nullable=True),
    sa.Column('buyer_bank_info', sa.String(length=200), nullable=True),
    sa.Column('total_amount', sa.String(length=50), nullable=True),
    sa.Column('total_tax', sa.String(length=50), nullable=True),
    sa.Column('amount_in_words', sa.String(length=100), nullable=True),
    sa.Column('amount_in_figures', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('payee', sa.String(length=50), nullable=True),
    sa.Column('reviewer', sa.String(length=50), nullable=True),
    sa.Column('issuer', sa.String(length=50), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('json_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_code', 'invoice_number', name='uix_invoice_code_number')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('specification', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('tax_rate', sa.String(length=20), nullable=True),
    sa.Column('tax', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('projects')
    # ### end Alembic commands ###
